### ISSUE TITLE
Positional mismatches in the InterVar output as compared to the original input vcf

### ISSUE THREAD

**Issue by AppWick-hub** [WGLab/InterVar#55]
Hi,
I have a query:
The generated InterVar output contains many variants (mostly indels) that have different positions than the original vcf file I am using. For example, a variant is located in **chr1:943526** _CTTTTTT (Ref) CTT,CTTT,CTTTT,C,CT,CTTTTT (Alt)_, But in the InterVar output the same variant is located in **chr1:943529-943532	TTTT (Ref) - (Alt)**. Another example, a variant located in **chr1:965337 CTTAT   C,*** in the original vcf but **chr1:965338-965341	TTAT -** in the InterVar output. How can I keep the variant position in the output file similar to the Input file?  

Thanks

**Comment by kaichop** [comment]
If you have multiple Alt allele in the same line, it is best to split them
into individual variants, and then do a left normalization, and then
perform annotation and interpretation.
If you run table_annovar in ANNOVAR, the original Ref/Alt and the new
Ref/Alt should be all in the tab-delimited output file.

**Comment by lincj1994** [comment]
@kaichop Actually, I have the same question. My input has 66,826 rows while the output has 67,208. After comparisons of the input and output, I found some of the rows were repeated by InterVar. 

Here is the input file (.tsv):
10 | 8111435 | 8111435 | G | A
10 | 8111561 | 8111562 | TG | T
10 | 43596172 | 43596172 | T | C
10 | 43597789 | 43597789 | G | T
10 | 45938987 | 45938987 | T | C

Here is the output file:
10 | 8111435 | 8111435 | G | A
10 | 8111561 | 8111562 | TG | T
10 | 8111561 | 8111562 | TG | T
10 | 43596172 | 43596172 | T | C
10 | 43597789 | 43597789 | G | T
10 | 45938987 | 45938987 | T | C

Here, TG>T was repeated twice.
I dont know if it is because of the format of input file.

**Comment by quanliustc** [comment]
when the variant belong to multiple genes, then  this variant will generate multiple lines, so for each gene, will have one line.
